### ISSUE TITLE
Doesn't look to work with yarn

### ISSUE THREAD

**Issue by felipenmoura** [jadjoubran/webdash#90] opened 2018-07-04 02:17 UTC
When using yarn to install packages, it is not listing the dependencies.
Actually, it says there are not even plugins installed. I had to install them all using npm for them to finally appear.

**Comment by jadjoubran** [comment] 2018-07-04 12:09
Hey @felipenmoura 
I assume you're referring to the `package json` plugin right?
Do you have a `yarn.lock` in the root of your folder? this is what that plugin uses to detect if you're using yarn or not
Also try running `yarn install` and then restart webdash.. does it work?

**Comment by felipenmoura** [comment] 2018-07-10 04:41
Hi.
Well, actually, no plugins appeared at all. It was like if I hadn't installed any.
I believe the problem was because I had both package-json.lock and yarn.lock.
I added the plugins using yarn, but webdash probably only looked at the package.json (what makes sense, I believe).
Then, when I installed the same plugins again, but using npm, they all appeared in the screen.

**Comment by felipenmoura** [comment] 2018-07-14 03:00
Hi.
Thanks, but still, something is just weird.

I did what you asked:
Installed everything in a clean directory using yarn
And it worked :)

Then, I installed a dependency using npm (like `npm install chalk` for example).
And the command `yarn webdash serv` stoped working. I had to install something using yarn again for it to start working again.

Well, anyways, I think  the right thing here is to be concise and install everything using the same tool, but it might be interesting for you to have it in mind, in case there is indeed some weird behave related to it ;)

**Comment by jadjoubran** [comment] 2018-07-14 09:14
Can you send me a screenshot of when you say it "stopped working" please?
this could be by design from npm/yarn but I'm not exactly sure what's going on
Thanks!

**Comment by felipenmoura** [comment] 2018-07-18 02:21
Sorry for not being clear about it.
It doesn't even start the service, with an error message saying that `webdash` doesn't exist (looks like npm cannot find it in the _node_modules_)

**Comment by jadjoubran** [comment] 2018-07-18 10:11
Alright thanks!
I'll close this issue for now since as you said it's not a good idea to use a mix of both
In case this issue happens with someone else, I can check if there's a potential fix for it

**Closed by jadjoubran** 2018-07-18 10:11 UTC
Labels: question
